#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x70FE17F8A643E15B (lukasa@keybase.io)
#
Name     : certifi
Version  : 2017.4.17
Release  : 26
URL      : https://pypi.debian.net/certifi/certifi-2017.4.17.tar.gz
Source0  : https://pypi.debian.net/certifi/certifi-2017.4.17.tar.gz
Source99 : https://pypi.debian.net/certifi/certifi-2017.4.17.tar.gz.asc
Summary  : Python package for providing Mozilla's CA Bundle.
Group    : Development/Tools
License  : ISC MPL-2.0
Requires: certifi-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Certifi: Python SSL Certificates
================================
`Certifi`_ is a carefully curated collection of Root Certificates for
validating the trustworthiness of SSL certificates while verifying the identity
of TLS hosts. It has been extracted from the `Requests`_ project.

%package python
Summary: python components for the certifi package.
Group: Default

%description python
python components for the certifi package.


%prep
%setup -q -n certifi-2017.4.17

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492525586
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492525586
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
